# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ShxAnUZhj5ARAQBSEjUVeQnMYW5lEDRn

Equation finding
"""

x = 12345
y = 543
z = 399

equation = 22*y+z
if  equation == x:
  print('it is a valid relation')

a = 5
b = int(input("enter the second no.:"))
c = int(input("enter the third no.:"))
if a // b == 1 and c // b == -2:
  print('both are correct')
else:
  print('none')

"""Finding the output of the given conditions"""

a = int(input("enter the first value: "))
b = int(input("enter the second value: "))
c = int(input("enter the third value: "))
a /= b # which is a = a / b
print(a)
c *= 5 # which is c = c * 5
print(c)

str="Data Science"
if str.find("s")!=-1:
  print("Found the string")
else:
  print("Not found!!!")

import math
print(math.pow(4,3))